add configurable healthcheck to container definition
liveflow-io/terraform-aws-ecs-datadog-agent pull request #2
Opened 2024-01-09 13:42 UTC by afhammad

2024-01-09 14:17 UTC, caioaao requested changes

2024-01-09 14:17 UTC, caioaao commented on variables.tf
> +}
since the agent is tied to a version here, maybe we could have the command hard coded and just have the variable `health_check_enabled` to control it?

2024-01-09 14:51 UTC, afhammad commented on variables.tf
> +}
considered it at first but figured its easier to modify the healthcheck config a level up without having to change it here

2024-01-11 10:55 UTC, evanob approved these changes

2024-01-11 10:55 UTC, merged